services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Repository\SlotRepository: '@App\Repository\InMemorySlotRepository'
    App\Query\SupplierAPI: '@App\Tests\Behat\StubSupplierAPI'

    App\Tests\Behat\:
        resource: '../tests/Behat/*'
